service: jobs-management

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  fetchAndStoreJobs:
    handler: src/fetchAndStoreJobs.ts
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-offline
